GET http://localhost:8080/books

###

GET http://localhost:8080/books/4

###

POST http://localhost:8080/books
Content-Type: application/json

{
    "id": "4",
    "title": "War and Peace",
    "author": "Leo Tolstoy",
    "quantity": 4
}

###

PATCH http://localhost:8080/checkout?id=4

###

PATCH http://localhost:8080/checkin?id=6