GET http://localhost:5000/api/books

###

GET http://localhost:5000/api/books/4

###

POST http://localhost:5000/api/books
Content-Type: application/json

{
    "id": "4",
    "title": "War and Peace",
    "author": "Leo Tolstoy",
    "quantity": 4
}

###

PATCH http://localhost:5000/api/checkout?id=4

###

PATCH http://localhost:5000/api/checkin?id=4