GET http://localhost:8080/api/books
X-API-Key: handshake
###

GET http://localhost:8080/api/books/4
X-API-Key: handshake
###

POST http://localhost:8080/api/books
Content-Type: application/json
X-API-Key: handshake

{
    "id": "4",
    "title": "War and Peace",
    "author": "Leo Tolstoy",
    "quantity": 4
}

###

PATCH http://localhost:8080/api/checkout?id=4
X-API-Key: handshake

###

PATCH http://localhost:8080/api/checkin?id=4
X-API-Key: handshake
